### PR TITLE
Regenerate build/ for bower

### PR DESCRIPTION
**Pull request by himdel**
Hi, doing `bower install moment-strftime` with 0.1.4 still gives me an old version, seems you have to regenerate the file in `build/`. I'm not sure how @Rudloff did that originally, but `uglify -s lib/moment-strftime.js -o build/moment-strftime.min.js` seems to work :).

@benjaminoakes could you please retag 0.1.4 to this after merging? (Or tag a new release..)

### CODE REVIEW

**Comment by Rudloff** [comment]
This library used to be in Coffeescript, so we needed a compiled version in the repo for Bower.
Now that it is entirely in JavaScript, I think shipping lib/moment-strftime.js is enough. We could drop the build folder, I guess.

**Comment by himdel** [comment]
Right, I guess there's no reason to minify this one :).

**Comment by martinpovolny** [comment]
Gentleman, can I do something to get this merged? I'd like to use it right now ;-)

**Comment by benjaminoakes** [comment]
Merged.  It sounds like we need to change `bower.json` too, but I'm not clear on what needs to happen there.

**Comment by himdel** [comment]
@benjaminoakes thanks, would you mind tagging a release please?

**Comment by benjaminoakes** [comment]
I already had a `v0.1.4` tag.  Does something else need to be done?  My apologies; I'm not very familiar with Bower.

**Comment by himdel** [comment]
The thing is, the `v0.1.4` tag points to the version with the [old file](https://github.com/benjaminoakes/moment-strftime/blob/v0.1.4/build/moment-strftime.min.js) in `build/`.

So when I do `bower install moment-strftime` it doesn't contain `lib/` or `spec/`, only `build/`. (And the other files). Thus installing moment-strftime via bower gives me the old version instead.

Maybe you can move the tag to the state after this ot merged, but probably the safer way is just to tag 0.1.5 now. Thanks :)

**Comment by himdel** [comment]
@benjaminoakes .. so the easiest way to fix it would be to `git tag v0.1.5` and `git push --tags` (and whatever else you do for a new release) .. unless you have an objection to doing a no-change release...

**Comment by benjaminoakes** [comment]
Done.  I released v0.1.5 via npm as well to avoid confusion.  Please let me know if you run into any further issues.

**Pull request merged**
